version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "22:10022"
    networks:
      - proxy_manager

networks:
  proxy_manager:
    external: true
